---
# Source: pitstop/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-app-common
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
data:
  Auth__Audience: pitstop-data-api
  Auth__Authority: https://auth.mattgerega.net
  Telemetry__Log__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana.svc.cluster.local:4317
  Telemetry__Metrics__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana.svc.cluster.local:4317
  Telemetry__Trace__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana.svc.cluster.local:4317
---
# Source: pitstop/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-app-data-api
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
data:
  FileStore__BaseUrl: https://filestore.mattgerega.net
  FileStore__Scope: filestore:read filestore:write
  FileStore__TokenEndpoint: https://auth.mattgerega.net/connect/token
  Telemetry__ActivitySourceName: PitStop.Data.Test.Activity
  Telemetry__MeterName: PitStop.Data.Test.Meter
  Telemetry__ServiceName: PitStop.Data.Test
---
# Source: pitstop/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-app-web
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
data:
  Telemetry__ActivitySourceName: PitStop.Web.Test.Activity
  Telemetry__MeterName: PitStop.Web.Test.Meter
  Telemetry__ServiceName: PitStop.Web.Test
---
# Source: pitstop/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: pitstop-app-data-api
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/service: pitstop-app-data-api
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: data-api
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/name: pitstop-app
---
# Source: pitstop/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: pitstop-app-web
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/service: pitstop-app-web
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: web
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/name: pitstop-app
---
# Source: pitstop/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-app-data-api
  labels:
    app.kubernetes.io/controller: data-api
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: data-api
      app.kubernetes.io/name: pitstop-app
      app.kubernetes.io/instance: pitstop-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 795e4e0912e984f131af644ef5ae611f75cc58efe0b42bd33d7336fa554e154f
      labels: 
        app.kubernetes.io/controller: data-api
        app.kubernetes.io/instance: pitstop-app
        app.kubernetes.io/name: pitstop-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - secretRef:
              name: data-api-secrets
          - configMapRef:
              name: pitstop-app-common
          - configMapRef:
              name: pitstop-app-data-api
          image: ghcr.io/spydersoft-consulting/pitstop-data-api:2.0.3-beta.24
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 5m
---
# Source: pitstop/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-app-web
  labels:
    app.kubernetes.io/controller: web
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: web
      app.kubernetes.io/name: pitstop-app
      app.kubernetes.io/instance: pitstop-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 795e4e0912e984f131af644ef5ae611f75cc58efe0b42bd33d7336fa554e154f
      labels: 
        app.kubernetes.io/controller: web
        app.kubernetes.io/instance: pitstop-app
        app.kubernetes.io/name: pitstop-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - env:
          - name: OidcProxySettings__ReverseProxy__Clusters__pitstopApi__Destinations__destination1__Address
            value: http://pitstop-app-data-api/
          envFrom:
          - secretRef:
              name: web-secrets
          - configMapRef:
              name: pitstop-app-common
          - configMapRef:
              name: pitstop-app-web
          image: ghcr.io/spydersoft-consulting/pitstop-web:2.0.3-beta.24
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 5m
---
# Source: pitstop/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pitstop-app
  labels:
    app.kubernetes.io/instance: pitstop-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pitstop-app
    app.kubernetes.io/version: 2.0.3-beta.24
    helm.sh/chart: pitstop-2.0.3-beta.24
  namespace: pitstop-test
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "pitstop.mattgerega.net"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: pitstop-app-web
        namespace: pitstop-test
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
