---
# Source: unifi-client/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-client
  labels:
    app.kubernetes.io/instance: unifi-client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-client
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-client-0.1.0
  namespace: stage
data:
  config.js: |
    window.unifi_client_api = {
      backend: 'https://api.mattgerega.org/unifi/ipmanager',
    };
  
    window.unifi_client_auth = {
      authority: 'https://auth.mattgerega.org/',
      clientId: 'unifiwebclient',
      redirectUri: 'https://uni.mattgerega.org',
    };
---
# Source: unifi-client/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: unifi-client
  labels:
    app.kubernetes.io/instance: unifi-client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-client
    app.kubernetes.io/service: unifi-client
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-client-0.1.0
  namespace: stage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: unifi-client
    app.kubernetes.io/name: unifi-client
---
# Source: unifi-client/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-client
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: unifi-client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-client
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-client-0.1.0
  namespace: stage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: unifi-client
      app.kubernetes.io/instance: unifi-client
  template:
    metadata:
      annotations: 
        checksum/configMaps: d9658bd755a860ba5bfacdff46327fc925e445567c91e5b51d869cf24d337dbf
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: unifi-client
        app.kubernetes.io/name: unifi-client
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - image: ghcr.io/spyder007/unifi-client:0.1.19
          imagePullPolicy: IfNotPresent
          name: main
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config.js
            name: config-js
            subPath: config.js
      volumes: 
        - configMap:
            name: unifi-client
          name: config-js
---
# Source: unifi-client/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi-client
  labels:
    app.kubernetes.io/instance: unifi-client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-client
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-client-0.1.0
  namespace: stage
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "uni.mattgerega.org"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: unifi-client
        namespace: stage
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
