---
# Source: identity/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-app-admin-api
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
data:
  IdentityServer__Authority: https://auth.mattgerega.net
  Serilog__MinimumLevel__Default: Information
  Telemetry__ActivitySourceName: Identity.Admin.Api.Test.Activity
  Telemetry__Log__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__MeterName: Identity.Admin.Api.Test.Meter
  Telemetry__Metrics__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__ServiceName: Identity.Admin.Api.Test
  Telemetry__Trace__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
---
# Source: identity/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-app-admin-ui
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
data:
  OidcProxySettings__Oidc__Authority: https://auth.mattgerega.net
  OidcProxySettings__Oidc__ClientId: identity.admin.frontend
  Serilog__MinimumLevel__Default: Information
  Telemetry__ActivitySourceName: Identity.Admin.Ui.Test.Activity
  Telemetry__Log__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__MeterName: Identity.Admin.Ui.Test.Meter
  Telemetry__Metrics__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__ServiceName: Identity.Admin.Ui.Test
  Telemetry__Trace__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
---
# Source: identity/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-app-identity
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
data:
  AllowedOrigins__0: https://*.mattgerega.net
  AllowedOrigins__1: http://localhost:3000
  Identity__AuthorityUrl: https://auth.mattgerega.net
  Resend__EmailFrom: Spydersoft Test
  Serilog__MinimumLevel__Default: Information
  Serilog__MinimumLevel__Override__Microsoft: Information
  Serilog__MinimumLevel__Override__System: Information
  Telemetry__ActivitySourceName: Identity.Test.Activity
  Telemetry__Log__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__MeterName: Identity.Test.Meter
  Telemetry__Metrics__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
  Telemetry__ServiceName: Identity.Test
  Telemetry__Trace__Otlp__Endpoint: http://nonproduction-grafana-alloy.grafana:4317
---
# Source: identity/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: identity-app-admin-api
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/service: identity-app-admin-api
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: admin-api
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/name: identity-app
---
# Source: identity/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: identity-app-admin-frontend
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/service: identity-app-admin-frontend
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: admin-frontend
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/name: identity-app
---
# Source: identity/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: identity-app-main
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/service: identity-app-main
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/name: identity-app
---
# Source: identity/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-app-main
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: identity-app
      app.kubernetes.io/instance: identity-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 8004354c3e8da351ca4f448fd3ad25f8c27d5d237401aa6f58098a8d86b5f645
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: identity-app
        app.kubernetes.io/name: identity-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - configMapRef:
              name: identity-app-identity
          - secretRef:
              name: identity-server-secrets
          image: ghcr.io/spyder007/identity_server:3.1.5-beta.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /livez
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: identity/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-app-admin-api
  labels:
    app.kubernetes.io/controller: admin-api
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: admin-api
      app.kubernetes.io/name: identity-app
      app.kubernetes.io/instance: identity-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 8004354c3e8da351ca4f448fd3ad25f8c27d5d237401aa6f58098a8d86b5f645
      labels: 
        app.kubernetes.io/controller: admin-api
        app.kubernetes.io/instance: identity-app
        app.kubernetes.io/name: identity-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - configMapRef:
              name: identity-app-admin-api
          - secretRef:
              name: identity-server-admin-api-secrets
          image: ghcr.io/spyder007/identity_admin_api:3.1.5-beta.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: identity/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-app-admin-frontend
  labels:
    app.kubernetes.io/controller: admin-frontend
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: admin-frontend
      app.kubernetes.io/name: identity-app
      app.kubernetes.io/instance: identity-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 8004354c3e8da351ca4f448fd3ad25f8c27d5d237401aa6f58098a8d86b5f645
      labels: 
        app.kubernetes.io/controller: admin-frontend
        app.kubernetes.io/instance: identity-app
        app.kubernetes.io/name: identity-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - env:
          - name: OidcProxySettings__ReverseProxy__Clusters__adminApi__Destinations__destination1__Address
            value: http://identity-app-admin-api/
          envFrom:
          - configMapRef:
              name: identity-app-admin-ui
          - secretRef:
              name: identity-server-admin-ui-secrets
          image: ghcr.io/spyder007/identity_admin_frontend:3.1.5-beta.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: identity/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: identity-app-admin-api
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "admin-api.auth.mattgerega.net"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: identity-app-admin-api
        namespace: platform-test
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
# Source: identity/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: identity-app-admin-frontend
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "admin.auth.mattgerega.net"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: identity-app-admin-frontend
        namespace: platform-test
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
# Source: identity/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: identity-app-main
  labels:
    app.kubernetes.io/instance: identity-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-app
    app.kubernetes.io/version: 3.1.5-beta.2
    helm.sh/chart: identity-3.1.5-beta.2
  namespace: platform-test
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "auth.mattgerega.net"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: identity-app-main
        namespace: platform-test
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
