name: rabbitmq-cluster-operator
version: 4.2.1
type: application
appVersion: 2.7.0
dependencies:
- repository: https://charts.bitnami.com/bitnami
  name: rabbitmq-cluster-operator
  version: 4.2.1
apiVersion: v2


