appVersion: 2.7.0
type: application
dependencies:
- version: 4.3.16
  name: rabbitmq-cluster-operator
  repository: https://charts.bitnami.com/bitnami
name: rabbitmq-cluster-operator
apiVersion: v2
version: 4.3.16


