type: application
dependencies:
- name: rabbitmq-cluster-operator
  version: 4.3.6
  repository: https://charts.bitnami.com/bitnami
version: 4.3.6
appVersion: 2.7.0
apiVersion: v2
name: rabbitmq-cluster-operator


