apiVersion: v2
appVersion: 2.7.0
name: rabbitmq-cluster-operator
version: 3.18.1
type: application
dependencies:
- repository: https://charts.bitnami.com/bitnami
  version: 3.18.1
  name: rabbitmq-cluster-operator


