name: rabbitmq-cluster-operator
appVersion: 2.7.0
type: application
version: 4.2.10
apiVersion: v2
dependencies:
- version: 4.2.10
  name: rabbitmq-cluster-operator
  repository: https://charts.bitnami.com/bitnami


