appVersion: 2.7.0
name: rabbitmq-cluster-operator
apiVersion: v2
type: application
version: 4.4.10
dependencies:
- version: 4.4.10
  name: rabbitmq-cluster-operator
  repository: https://charts.bitnami.com/bitnami


