apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  secretBackend:
    externalSecret:
      name: {{ .Release.Name }}-user
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 100m
      memory: 500Mi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: nfs-client
    storage: "5Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - {{ .Release.Name }}
        topologyKey: kubernetes.io/hostname
#   override:
#     statefulSet:
#       spec:
#         template:
#           spec:
#             containers: []
#             topologySpreadConstraints:
#             - maxSkew: 1
#               topologyKey: "topology.kubernetes.io/zone"
#               whenUnsatisfiable: DoNotSchedule
#               labelSelector:
#                 matchLabels:
#                   app.kubernetes.io/name: {{ .Release.Name }}