apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-user-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-user
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        default_user.conf: |-
          default_user={{`"{{ .username }}"`}}
          default_pass={{`"{{ .password }}"`}}
        host: {{ .Release.Name }}.rabbitmq.svc
        password: {{`"{{ .password }}"`}}
        port: "5672"
        provider: rabbitmq
        type: rabbitmq
        username: {{`"{{ .username }}"`}}
  data:
  - secretKey: password
    remoteRef:
      key: secrets-k8/rabbitmq/{{ .Values.environment }}
      property: password
  - secretKey: username
    remoteRef:
      key: secrets-k8/rabbitmq/{{ .Values.environment }}
      property: username