apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nonproduction-cluster-resources
  labels:
    spydersoft.io/environment: non-production
    spydersoft.io/category: resources
spec:
  destination:
    namespace: cluster-tools
    server: https://cp-nonprod.gerega.net:6443
  project: cluster-tools
  source:
    path: cluster-resources
    repoURL: https://github.com/spydersoft-consulting/ops-nonprod-cluster
    targetRevision: HEAD

    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
