apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: identity-apps-nonprod
  labels:
    spydersoft.io/environment: non-production
    spydersoft.io/category: app
spec:
  generators:
  - git:
      repoURL: https://bitbucket.org/spydersoftteam/ops-nonprod-cluster
      revision: HEAD
      directories:
      - path: apps/identity/test/*
      - path: apps/identity/stage/*
  template:
    metadata:
      name: '{{path.basename}}-{{path[2]}}'
      labels:
        spydersoft.io/environment: non-production
        spydersoft.io/category: app
    spec:
      project: identity-apps
      source:
        repoURL: https://bitbucket.org/spydersoftteam/ops-nonprod-cluster
        targetRevision: main
        path: '{{ path }}'
        directory:
          recurse: true
      destination:
        server: https://192.168.1.43:6443
        namespace: '{{ path[2] }}'
      syncPolicy:
        automated: 
          prune: true 
          selfHeal: true
        syncOptions:   
        - CreateNamespace=true
      