apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nonproduction-apps
  labels:
    spydersoft.io/environment: non-production
    spydersoft.io/category: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/spydersoft-consulting/ops-nonprod-cluster
        revision: HEAD
        directories:
          - path: apps/**/**/*

  template:
    metadata:
      name: "{{path.basename}}-{{path[2]}}"
      labels:
        spydersoft.io/environment: non-production
        spydersoft.io/category: app
    spec:
      project: "{{ path[1] }}-apps"
      source:
        repoURL: https://github.com/spydersoft-consulting/ops-nonprod-cluster
        targetRevision: main
        path: "{{ path }}"
        directory:
          recurse: true
      destination:
        server: https://cp-nonprod.gerega.net:6443
        namespace: "{{ path[2] }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
