---
# Source: unifi-ipmanager/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ipmanager
  labels:
    app.kubernetes.io/instance: unifi-ipmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-ipmanager-0.1.0
  namespace: stage
data:
  Identity__ApiName: unifi.ipmanager
  Telemetry__ActivitySourceName: Unifi.IpManager.Stage.Activity
  Telemetry__MeterName: Unifi.IpManager.Stage.Meter
  Telemetry__ServiceName: Unifi.IpManager.Stage
  UnifiControllerOptions__DnsZone: gerega.net
  UnifiControllerOptions__Url: https://unifi.gerega.net
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: unifi-ipmanager
  labels:
    app.kubernetes.io/instance: unifi-ipmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager
    app.kubernetes.io/service: unifi-ipmanager
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-ipmanager-0.1.0
  namespace: stage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: unifi-ipmanager
    app.kubernetes.io/name: unifi-ipmanager
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-ipmanager
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: unifi-ipmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-ipmanager-0.1.0
  namespace: stage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: unifi-ipmanager
      app.kubernetes.io/instance: unifi-ipmanager
  template:
    metadata:
      annotations: 
        checksum/configMaps: b5d79b3ea170a9673a1abf9a3e7f88ff894f9c49ac656b43b948cb58c882b00f
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: unifi-ipmanager
        app.kubernetes.io/name: unifi-ipmanager
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - configMapRef:
              name: home-automation-common-config
          - configMapRef:
              name: unifi-ipmanager
          - secretRef:
              name: unifi-secrets
          image: ghcr.io/spyder007/unifi-ipmanager:1.1.1-128
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi-ipmanager
  labels:
    app.kubernetes.io/instance: unifi-ipmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: unifi-ipmanager-0.1.0
  namespace: stage
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "api.mattgerega.org"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: unifi-ipmanager
        namespace: stage
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /unifi/ipmanager
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
              type: ReplacePrefixMatch
