---
# Source: pitstop-data/templates/data-api-es.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-api-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: data-api-secrets
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        ConnectionStrings__pitstop-db: "Host=pitstop-data-postgres;Database=pitstop;Username={{ .db_user }};Password={{ .db_password }}"
        FileStore__ClientId: "{{ .data_api_clientid }}"
        FileStore__ClientSecret: "{{ .data_api_clientsecret }}"
        Notification__ClientId: "{{ .data_api_clientid }}"
        Notification__ClientSecret: "{{ .data_api_clientsecret }}"
  data:
  - secretKey: db_user
    remoteRef:
      key: secrets-k8/pitstop/test/postgres
      property: user
  - secretKey: db_password
    remoteRef:
      key: secrets-k8/pitstop/test/postgres
      property: password
  - secretKey: data_api_clientid
    remoteRef:
      key: secrets-k8/pitstop/test/data-api-client
      property: clientid
  - secretKey: data_api_clientsecret
    remoteRef:
      key: secrets-k8/pitstop/test/data-api-client
      property: clientsecret
