apiVersion: v1
kind: Namespace
metadata:
  name: stage
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cr-spydersoft-github
  namespace: stage
  labels:
    name: github-cr-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          name: stage
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secrets-k8/github-cr-config
        property: config
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
